- oldRepoName: tac
  newRepoName: tac
  description: This is a top level group.
  structure: Technical Advisory Council
  leads:
    - name: Christopher "CRob" Robinson
      githubId: SecurityCRob
      url: https://github.com/SecurityCRob
- oldRepoName: wg-best-practices-os-developers
  newRepoName: wg-best-practices
  description: This is a top level group
  structure: 1
  leads:
    - name: Christopher "CRob" Robinson
      githubId: SecurityCRob
      url: https://github.com/SecurityCRob
- oldRepoName: wg-vulnerability-disclosures
  newRepoName: wg-vulnerability-disclosures
  description: >
    This is a top level group.
  structure: 2
  leads:
    - name: Christopher "CRob" Robinson
      githubId: SecurityCRob
      url: https://github.com/SecurityCRob
- oldRepoName: wg-endusers
  newRepoName: wg-endusers
  description: This is a top level group
  structure: 3
  lead: >
    - Jonathan Meadows with Github ID: [jonmuk](https://github.com/jonmuk)
- oldRepoName: wg-identifying-security-threats
  newRepoName: wg-identifying-security-threats
  description: >
    This is a top level group.
  structure: 4
  leads:
    - name: Michael Scovetta
      githubId: scovetta
      url: https://github.com/scovetta
- oldRepoName: wg-security-tooling
  newRepoName: wg-security-tooling
  structure: 5
  description: >
    This is a top level group.
  leads:
    - name: Josh Bressers
      githubId: joshbressers
      url: https://github.com/joshbressers
- oldRepoName: wg-securing-software-repos
  newRepoName: wg-securing-software-repos
  description: >
    This is a top level group.
  structure: 6
  leads:
    - name: Dustin Ingram
      githubId: di
      url: https://github.com/di
- oldRepoName: wg-supply-chain-integrity
  newRepoName: wg-supply-chain-integrity
  description: >
    This is a top level group.
  structure: 7
  leads:
    - name: Kim Lewandowski
      githubId: kimsterv
      url: https://github.com/kimsterv
    - name: Dan Lorenc
      githubId: dlorenc
      url: https://github.com/dlorenc
- oldRepoName: wg-securing-critical-projects
  newRepoName: wg-securing-critical-projects
  description: >
    This is a top level group.
  structure: 8
  leads:
    - name: Jeff Mendoza
      githubId: jeffmendoza
      url: https://github.com/jeffmendoza
    - name: Amir Hossin Montazery
      githubId: amirhmh3
      url: https://github.com/amirhmh3

- oldRepoName: secure-sw-dev-fundamentals
  newRepoName: sig-secure-sw-dev-fundamentals
  description: >
    This is under the Best Practices working group. Full name is Secure Software Development Fundamentals courses SIG.
  structure: 1-A
  leads:
    - name: David Wheeler
      githubId: david-a-wheeler
      url: https://github.com/david-a-wheeler
- oldRepoName: scorecard
  newRepoName: project-scorecard
  description: >
    This is under the Best Practices working group.
  structure: 1-D
  leads:
    - name: Azeem Shaikh
      githubId: azeemshaikh38
      url: https://github.com/azeemshaikh38
    - name: Laurent Simon
      githubId: laurentsimon
      url: https://github.com/laurentsimon
    - name: Naveen Srinivasan
      githubId: naveensrinivasan
      url: https://github.com/naveensrinivasan
    - name: Risto McGehee
      githubId: chrismcgehee
      url: https://github.com/chrismcgehee
    - name: Stephen Augustus
      githubId: justaugustus
      url: https://github.com/justaugustus
- oldRepoName: great-mfa-project
  newRepoName: sig-secure-sw-dev-fundamentals
  description: >
    This is under the Best Practices working group.
  structure: 1-E
  leads:
    - name: Christopher "CRob" Robinson
      githubId: SecurityCRob
      url: https://github.com/SecurityCRob
- oldRepoName: Memory-Safety
  newRepoName: sig-memory-Safety
  description: >
    This is under the Best Practices working group.
  structure: 1-AJ
  leads:
    - name: Nell Shamrell-Harrington
      githubId: nellshamrell
      url: https://github.com/nellshamrell
- oldRepoName: criticality_score
  newRepoName: project-criticality_score
  description: >
    This is under wg-securing-critical-projects
  structure: 8-AA
  leads:
    - name: Jeff Mendoza
      githubId: jeffmendoza
      url: https://github.com/jeffmendoza
    - name: Amir Hossin Montazery
      githubId: amirhmh3
      url: https://github.com/amirhmh3
- oldRepoName: package-feeds
  newRepoName: project-package-feeds
  description: >
    This is under wg-securing-critical-projects
  structure: 8-AC
  leads:
    - name: Jeff Mendoza
      githubId: jeffmendoza
      url: https://github.com/jeffmendoza
    - name: Amir Hossin Montazery
      githubId: amirhmh3
      url: https://github.com/amirhmh3
- oldRepoName: package-analysis
  newRepoName: project-package-analysis
  description: >
    This is under wg-securing-critical-projects
  structure: 8-AC
  leads:
    - name: Jeff Mendoza
      githubId: jeffmendoza
      url: https://github.com/jeffmendoza
    - name: Amir Hossin Montazery
      githubId: amirhmh3
      url: https://github.com/amirhmh3
- oldRepoName: Project-Security-Metrics
  newRepoName: project-project-Security-Metrics
  description: >
    This is under wg-identifying-security-threats
  structure: 2-O
  leads:
    - name: Michael Scovetta
      githubId: scovetta
      url: https://github.com/scovetta
- oldRepoName: security-insights-spec
  newRepoName: project-security-insights-spec
  description: >
    This is under wg-identifying-security-threats
  structure: 2-N
  leads:
    - name: Christopher "CRob" Robinson
      githubId: SecurityCRob
      url: https://github.com/SecurityCRob
- oldRepoName: s2c2f
  newRepoName: sig-secure-supply-chain-consumption-framework
  description: >
    This is under wg-supply-chain-integrity
  structure: 7-Y
  leads:
    - name: Jay White
      githubId: camaleon2016
      url: https://github.com/camaleon2016
    - name: Adrian Diglio
      githubId: adriandiglio
      url: https://github.com/adriandiglio
    - name: Jasmine Wang
      githubId: jasminewang0
      url: https://github.com/jasminewang0
- oldRepoName: fuzz-introspector
  newRepoName: sig-fuzz-introspector
  description: >
    This is under wg-security-tooling
  structure: 5-U
  leads:
    - name: Josh Bressers
      githubId: joshbressers
      url: https://github.com/joshbressers
- oldRepoName: allstar
  newRepoName: project-allstar
  description: >
    This is under wg-securing-critical-projects
  structure: 8-AD
  leads:
    - name: Jeff Mendoza
      githubId: jeffmendoza
      url: https://github.com/jeffmendoza
    - name: Amir Hossin Montazery
      githubId: amirhmh3
      url: https://github.com/amirhmh3
- oldRepoName: oss-vulnerability-guide
  newRepoName: sig-oss-vulnerability-guide
  description: >
    This is under wg-vulnerability-disclosures
  structure: 2-I
  leads:
    - name: Christopher "CRob" Robinson
      githubId: SecurityCRob
      url: https://github.com/SecurityCRob
- oldRepoName: osv-schema
  newRepoName: project-osv-schema
  description: This is under wg-vulnerability-disclosures
  structure: 2-K
  leads:
    - name: Christopher "CRob" Robinson
      githubId: SecurityCRob
      url: https://github.com/SecurityCRob
- oldRepoName: DEI-SIG
  newRepoName: sig-dei
  description: TBD
  structure: TBD
  leads:
    - name: Christopher "CRob" Robinson
      githubId: SecurityCRob
      url: https://github.com/SecurityCRob
