- oldRepoName: tac
  newRepoName: tac
  slack_name: tac
  slack_link: https://openssf.slack.com/archives/C01AAV2TTEG
  meeting-time: every other Tuesday 11:00a ET
  zoom: https://zoom-lfx.platform.linuxfoundation.org/meeting/94234355704?password=939d8506-7e58-4072-89e3-6b59259ee9db
  notes: https://docs.google.com/document/d/1JY8FREBPCUUFpuv7-4B9EjeS2MLDpel0dbG5DFWrTns/edit?usp=drive_link
  description: >
    The OpenSSF Technical Advisory Council is responsible for oversight of the various Technical Initiatives (TI) of the OpenSSF.
  structure: Technical Advisory Council
  leads:
    - name: Christopher CRob Robinson
      githubId: SecurityCRob
      url: https://github.com/SecurityCRob
  sigs:
    - name: Secure Software Development Fundamentals
      url: https://openssf.org/training/courses/
    - name: Concise & Best Practices Guides
      url: https://openssf.org/resources/guides/
    - name: Education
      url: https://github.com/ossf/education
    - name: Memory Safety
      url: https://github.com/ossf/Memory-Safety
    - name: Security Toolbelt
      url: https://github.com/ossf/toolbelt
  projects:
    - name: OpenSSF Best Practices Badge
      url: https://bestpractices.coreinfrastructure.org
    - name: OpenSSF Scorecard
      url: https://github.com/ossf/scorecard
    - name: Security Knowledge Framework 'SKF'
      url: https://www.securityknowledgeframework.org/#:~:text=part%20of%20the-,OpenSSF,-Working%20group%3A%20Best
    - name: Common Requirements Enumeration
      url: https://github.com/OWASP/OpenCRE
- oldRepoName: wg-best-practices-os-developers
  newRepoName: wg-best-practices-os-developers
  logo: best_logo.png
  slack_name: wg_best_practices_ossdev
  slack_link: https://openssf.slack.com/archives/C01AHCRP8BT
  meeting-time: None
  zoom: https://zoom-lfx.platform.linuxfoundation.org/meeting/97123533582?password=51bc1484-f12d-4382-b768-6d8f3c9b08c2
  notes: https://docs.google.com/document/d/1JY8FREBPCUUFpuv7-4B9EjeS2MLDpel0dbG5DFWrTns/edit?usp=drive_link
  description: >
    Want to help drive open source security education or help develop best practices? We have a lot of projects and groups that are working towards these goals.
  leads:
    - name: Christopher CRob Robinson
      githubId: SecurityCRob
      url: https://github.com/SecurityCRob
  sigs:
    - name: Secure Software Development Fundamentals
      url: https://openssf.org/training/courses/
    - name: Security Knowledge Framework 'SKF'
      url: https://www.securityknowledgeframework.org/#:~:text=part%20of%20the-,OpenSSF,-Working%20group%3A%20Best
    - name: Common Requirements Enumeration
      url: https://github.com/OWASP/OpenCRE
    - name: Concise & Best Practices Guides
      url: https://openssf.org/resources/guides/
    - name: Education
      url: https://github.com/ossf/education
    - name: Memory Safety
      url: https://github.com/ossf/Memory-Safety
    - name: Security Toolbelt
      url: https://github.com/ossf/toolbelt
  projects:
    - name: OpenSSF Best Practices Badge
      url: https://bestpractices.coreinfrastructure.org
    - name: OpenSSF Scorecard
      url: https://github.com/ossf/scorecard
- oldRepoName: ai-ml-security
  newRepoName: ai-ml-security
  slack_name: wg_ai_ml_security
  slack_link: https://openssf.slack.com/archives/C0587E513KR
  meeting-time: every other Monday 1:00p ET
  zoom: https://zoom-lfx.platform.linuxfoundation.org/meeting/97349085860?password=3d2b70af-6d20-4b45-ac5b-de4e99e964ae
  notes: https://docs.google.com/document/d/1YNP-XJ9jpTjM6ekKOBgHH8-avAws2DVKeCpn858siiQ/edit#heading=h.l453rgplh0xw
  description: >
    We formed in September 2023 after the growing problem of AI/ML Security in open source. Join is to discuss the possible security impacts of AI / ML technologies on open source software, maintainers, communities, and their adopters, along with how OSS projects could safely or effectively leverage LLMs to improve their security posture.
  leads:
    - name: Mihai Maruseac
      githubId: mihaimaruseac
      url: https://github.com/mihaimaruseac
- oldRepoName: wg-vulnerability-disclosures
  newRepoName: wg-vulnerability-disclosures
  logo: vuln_logo.png
  slack_name: wg_vulnerability_disclosures
  slack_link: https://openssf.slack.com/archives/C019Y2A28Q6
  meeting-time: every other Wednesday 11:00a ET
  zoom: https://zoom-lfx.platform.linuxfoundation.org/meeting/93701721327?password=a2e18922-298a-4d84-ba1f-55af95f0f5cc
  notes: https://docs.google.com/document/d/1AXkapzjZ-SxwcBN7rZeSstkzdapd3sbzfHDxz6A59Ic/edit
  description: >
    We are improving the overall security of the OSS ecosystem by helping advance vulnerability reporting and communication.
  leads:
    - name: Christopher CRob Robinson
      githubId: SecurityCRob
      url: https://github.com/SecurityCRob
  sigs:
    - name: CVD Guides
      url: https://github.com/ossf/oss-vulnerability-guide
    - name: SIRT
      url: https://github.com/ossf/SIRT
    - name: OpenVEX
      url: https://github.com/ossf/OpenVEX
    - name: Vuln Autofix SIG
      url: https://docs.google.com/document/d/1_QwN7yQXWGM2tJaostIRNqyZIhVceVlIyXqCrSdC4E8/edit?usp=drive_link
  projects:
    - name: Open Source Vuln Schema 'OSV'
      url: https://github.com/ossf/osv-schema
- oldRepoName: wg-dei
  newRepoName: wg-dei
  slack_name: wg_dei
  slack_link: https://openssf.slack.com/archives/C068TF7AH0U
  meeting-time: every other Tuesday 11:00a ET
  zoom: https://zoom-lfx.platform.linuxfoundation.org/meeting/98853031629?password=a356aa22-ab31-4e2e-a8a0-9ecb45af84bd
  notes: https://docs.google.com/document/d/1zGTOJdFVIMnixT3EFQ6_bbQ0iy7f4Z4TxhX9A5VY9TM/edit
  description: >
    We formed in December 2023 to help increase representation and strengthen the overall effectiveness of the cybersecurity workforce.
  leads:
    - name: Jay White
      githubId: camaleon2016
      url: https://github.com/camaleon2016
  sigs:
    - name: Secure Software Development Fundamentals
      url: https://openssf.org/training/courses/
    - name: Security Knowledge Framework 'SKF'
      url: https://www.securityknowledgeframework.org/#:~:text=part%20of%20the-,OpenSSF,-Working%20group%3A%20Best
    - name: Common Requirements Enumeration
      url: https://github.com/OWASP/OpenCRE
    - name: Concise & Best Practices Guides
      url: https://openssf.org/resources/guides/
    - name: Education
      url: https://github.com/ossf/education
    - name: Memory Safety
      url: https://github.com/ossf/Memory-Safety
    - name: Security Toolbelt
      url: https://github.com/ossf/toolbelt
  projects:
    - name: OpenSSF Best Practices Badge
      url: https://bestpractices.coreinfrastructure.org
    - name: OpenSSF Scorecard
      url: https://github.com/ossf/scorecard
- oldRepoName: wg-endusers
  newRepoName: wg-endusers
  slack_name: wg_end_users
  slack_link: https://openssf.slack.com/archives/C03488JMKNX
  meeting-time: every Monday 12:30p ET
  zoom: https://zoom-lfx.platform.linuxfoundation.org/meeting/95757110915?password=21683129-f958-4ea8-a36d-1fffaa06f49c
  notes: https://docs.google.com/document/d/1JrKetG5zeDqUn9n7SKI3L0oR-S9k0r4YMHFcqhZ7WNU/edit?usp=sharing
  description: >
    We represent the interests of public and private sector organizations that primarily consume open source rather than produce it. Right now, we are focusing on threat modeling. Join us to see how threat modeling works and get your ideas in the current scope.
  leads:
    - name: Jonathan Meadows
      githubId: jonmuk
      url: https://github.com/jonmuk
  sigs:
    - name: Threat Modeling
      url: https://docs.google.com/document/d/1abI65H4pF5y8YtA2_TuDBAaI47v9mTfpr5mwVvccX_I/edit
- oldRepoName: wg-identifying-security-threats
  newRepoName: wg-identifying-security-threats
  slack_name: wg_identifying_security_threats
  slack_link: https://openssf.slack.com/archives/C01A50B978T
  meeting-time: every other Wednesday 1:00p ET
  zoom: https://zoom-lfx.platform.linuxfoundation.org/meeting/99771890101?password=9f10219a-9545-4047-80fb-b5ca75bc850c
  notes: https://docs.google.com/document/d/1XimygAYGbG2aofAiBD9--ZMTALdnbdbVw53R851ZZKY/edit?usp=sharing
  description: >
    Now called Metrics & Metadata! We enable informed confidence in the security of OSS by collecting, curating, and communicating relevant metrics and metadata. Our WG has mostly projects that focus on the code to get this done.
  leads:
    - name: Michael Scovetta
      githubId: scovetta
      url: https://github.com/scovetta
  projects:
    - name: Security Insights
      url: https://github.com/ossf/security-insights-spec
    - name: 'Security-Metrics: Risk Dashboard'
      url: https://github.com/ossf/Project-Security-Metrics
    - name: Security Reviews
      url: https://github.com/ossf/security-reviews
    - name: Security Insights Spec
      url: https://github.com/ossf/security-insights-spec
- oldRepoName: wg-security-tooling
  newRepoName: wg-security-tooling
  slack_name: wg_security_tooling
  slack_link: https://openssf.slack.com/archives/C019Q1VEA87
  meeting-time: every other Friday 11:00a ET
  zoom: https://zoom-lfx.platform.linuxfoundation.org/meeting/94897563315?password=7f03d8e7-7bc9-454e-95bd-6e1e09cb3b0b
  notes: https://docs.google.com/document/d/1bFpHEbbEUf2rWiYXQY7cGg1HrmI9TqwaD8U_3Hi9A8I/edit?usp=sharing
  description: >
    Our mission is to provide the best security tools for open source developers and make them universally accessible. We talk a lot about SBOMs currently.
  leads:
    - name: Ryan Ware
      githubId: ware
      url: https://github.com/ware
  sigs:
    - name: SBOM Everywhere
      url: https://drive.google.com/drive/folders/154MCLeIOQEgPpTUL7yzplOiipBVJ5KZJ
    - name: OSS Fuzzing
      url: https://docs.google.com/document/d/1TmhqYpB1Ly-5o-F31RVHxgpunW6qeDTVopBCtCmKhs0/edit
  projects:
    - name: SBOMit
      url: https://github.com/sbomit
- oldRepoName: wg-securing-software-repos
  newRepoName: wg-securing-software-repos
  slack_name: wg_securing_software_repos
  slack_link: https://openssf.slack.com/archives/C034CBLMQ9G
  meeting-time: every 4 weeks on Wednesday at 6:00p ET and every 4 weeks on Thursday at 9:00pa ET 
  zoom: https://zoom-lfx.platform.linuxfoundation.org/meeting/98058137343?password=28dafc6e-cfcf-440d-bb63-ca73a1739f06
  notes: https://docs.google.com/document/d/1HzA4M4toiExUYQAkuLqimy4EuuunHagUQ7rZKJDb1Os/edit?usp=sharing
  description: >
    We provide a collaborative environment for aligning on the introduction of new tools and technologies to strengthen and secure software repositories. Our current project is Repository Service for TUF, join to learn more.
  leads:
    - name: Dustin Ingram
      githubId: di
      url: https://github.com/di
  projects:
    - name: RSTUF
      url: https://github.com/repository-service-tuf
- oldRepoName: wg-supply-chain-integrity
  newRepoName: wg-supply-chain-integrity
  slack_name: wg_supply_chain_integrity
  slack_link: https://openssf.slack.com/archives/C01A1MA7A1K
  meeting-time: every other Wednesday 12:00p ET
  zoom: https://zoom-lfx.platform.linuxfoundation.org/meeting/96297611656?password=f030337b-dc4d-43d4-ac55-26db510f3d1c
  notes: https://docs.google.com/document/d/1NzmoZFuyPKmmX7P1GXADfNNmHFDkGHXyE0TfQFX2daw/edit?usp=sharing
  description: >
    We are helping people understand and make decisions on the provenance of the code they maintain, produce and use. We have great projects like GUAC, SLSA and gittuf that you can work with.
  leads:
    - name: Isaac Hepworth
      githubId: hepwori
      url: https://github.com/hepwori
    - name: Dan Lorenc
      githubId: dlorenc
      url: https://github.com/dlorenc
  sigs:
    - name: S2C2F
      url: https://github.com/ossf/s2c2f
  projects:
    - name: SLSA
      url: https://slsa.dev/
    - name: gittuf
      url: https://github.com/gittuf/gittuf
    - name: GUAC
      url: https://github.com/guacsec/guac   
- oldRepoName: wg-securing-critical-projects
  newRepoName: wg-securing-critical-projects
  slack_name: wg_securing_critical_projects
  slack_link: https://openssf.slack.com/archives/C019Y2AR76J
  meeting-time: every 4 weeks on Thursday 12:00p ET
  zoom: https://zoom-lfx.platform.linuxfoundation.org/meeting/95053207038?password=41a2966d-c96b-42d3-b2ee-635fc1dbaf51
  notes: https://docs.google.com/document/d/1j_efLVDXGoKgfHHZbJtpBxd_Gso1ghHBdK3NfEVc15o/edit?usp=sharing
  description: >
    Wonder how critical OSS projects are selected? Then join us! We have progress reports every other week on each project/SIG so it is easy to jump in and get going.
  leads:
    - name: Jeff Mendoza
      githubId: jeffmendoza
      url: https://github.com/jeffmendoza
    - name: Amir Hossin Montazery
      githubId: amirhmh3
      url: https://github.com/amirhmh3
  sigs:
    - name: List of Critical OS Prj, components, & Frameworks
      url: https://docs.google.com/spreadsheets/d/1ONZ4qeMq8xmeCHX03lIgIYE4MEXVfVL6oj05lbuXTDM/edit
    - name: Harvard study
      url: https://www.coreinfrastructure.org/programs/census-program-ii/
  projects:
    - name: criticality_score
      url: https://github.com/ossf/criticality_score
    - name: Package Analysis/Feeds
      url: https://github.com/ossf/package-analysis
    - name: Allstar
      url: https://github.com/ossf/allstar