name: Generate Readme
on: [push]
jobs:
    update_templates:
      name: "Update Readme"
      runs-on: ubuntu-latest
      steps:
        - name: "📥  Fetching Repository Contents"
          uses: actions/checkout@main
  
        - name: "💾  Github Repository Metadata"
          uses: ossf/wg-vulnerability-disclosures@main
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
        - name: "💫  Dynamic Readme Render"
          uses: ossf/wg-vulnerability-disclosures@main
          with:
            GLOBAL_TEMPLATE_REPOSITORY: {repository-owner}/{repository-name}
            files: |
              README.md
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}